/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Avatar SDK
 * Heygen Streaming Avatar
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@heygen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NewSessionIceServers2 } from './NewSessionIceServers2';
import {
    NewSessionIceServers2FromJSON,
    NewSessionIceServers2FromJSONTyped,
    NewSessionIceServers2ToJSON,
} from './NewSessionIceServers2';
import type { Sdp } from './Sdp';
import {
    SdpFromJSON,
    SdpFromJSONTyped,
    SdpToJSON,
} from './Sdp';

/**
 * 
 * @export
 * @interface NewSessionData
 */
export interface NewSessionData {
    /**
     * 
     * @type {string}
     * @memberof NewSessionData
     */
    sessionId?: string;
    /**
     * 
     * @type {Sdp}
     * @memberof NewSessionData
     */
    sdp?: Sdp;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewSessionData
     */
    iceServers?: Array<string>;
    /**
     * 
     * @type {Array<NewSessionIceServers2>}
     * @memberof NewSessionData
     */
    iceServers2?: Array<NewSessionIceServers2>;
}

/**
 * Check if a given object implements the NewSessionData interface.
 */
export function instanceOfNewSessionData(value: object): boolean {
    return true;
}

export function NewSessionDataFromJSON(json: any): NewSessionData {
    return NewSessionDataFromJSONTyped(json, false);
}

export function NewSessionDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewSessionData {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['session_id'] == null ? undefined : json['session_id'],
        'sdp': json['sdp'] == null ? undefined : SdpFromJSON(json['sdp']),
        'iceServers': json['ice_servers'] == null ? undefined : json['ice_servers'],
        'iceServers2': json['ice_servers2'] == null ? undefined : ((json['ice_servers2'] as Array<any>).map(NewSessionIceServers2FromJSON)),
    };
}

export function NewSessionDataToJSON(value?: NewSessionData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'session_id': value['sessionId'],
        'sdp': SdpToJSON(value['sdp']),
        'ice_servers': value['iceServers'],
        'ice_servers2': value['iceServers2'] == null ? undefined : ((value['iceServers2'] as Array<any>).map(NewSessionIceServers2ToJSON)),
    };
}

