/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Avatar SDK
 * Heygen Streaming Avatar
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: api@heygen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InterruptResponse
 */
export interface InterruptResponse {
    /**
     * 
     * @type {string}
     * @memberof InterruptResponse
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof InterruptResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the InterruptResponse interface.
 */
export function instanceOfInterruptResponse(value: object): value is InterruptResponse {
    return true;
}

export function InterruptResponseFromJSON(json: any): InterruptResponse {
    return InterruptResponseFromJSONTyped(json, false);
}

export function InterruptResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InterruptResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function InterruptResponseToJSON(value?: InterruptResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

