/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Avatar SDK
 * Heygen Streaming Avatar
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: api@heygen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InterruptResponseData
 */
export interface InterruptResponseData {
    /**
     * 
     * @type {string}
     * @memberof InterruptResponseData
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof InterruptResponseData
     */
    message?: string;
}

/**
 * Check if a given object implements the InterruptResponseData interface.
 */
export function instanceOfInterruptResponseData(value: object): value is InterruptResponseData {
    return true;
}

export function InterruptResponseDataFromJSON(json: any): InterruptResponseData {
    return InterruptResponseDataFromJSONTyped(json, false);
}

export function InterruptResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InterruptResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function InterruptResponseDataToJSON(value?: InterruptResponseData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

