/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Avatar SDK
 * Heygen Streaming Avatar
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: api@heygen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewSessionRequestVoice
 */
export interface NewSessionRequestVoice {
    /**
     * 
     * @type {string}
     * @memberof NewSessionRequestVoice
     */
    voiceId?: string;
    /**
     * 
     * @type {number}
     * @memberof NewSessionRequestVoice
     */
    rate?: number;
    /**
     * 
     * @type {string}
     * @memberof NewSessionRequestVoice
     */
    emotion?: NewSessionRequestVoiceEmotionEnum;
}


/**
 * @export
 */
export const NewSessionRequestVoiceEmotionEnum = {
    Excited: 'Excited',
    Serious: 'Serious',
    Friendly: 'Friendly',
    Soothing: 'Soothing',
    Broadcaster: 'Broadcaster'
} as const;
export type NewSessionRequestVoiceEmotionEnum = typeof NewSessionRequestVoiceEmotionEnum[keyof typeof NewSessionRequestVoiceEmotionEnum];


/**
 * Check if a given object implements the NewSessionRequestVoice interface.
 */
export function instanceOfNewSessionRequestVoice(value: object): value is NewSessionRequestVoice {
    return true;
}

export function NewSessionRequestVoiceFromJSON(json: any): NewSessionRequestVoice {
    return NewSessionRequestVoiceFromJSONTyped(json, false);
}

export function NewSessionRequestVoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewSessionRequestVoice {
    if (json == null) {
        return json;
    }
    return {
        
        'voiceId': json['voice_id'] == null ? undefined : json['voice_id'],
        'rate': json['rate'] == null ? undefined : json['rate'],
        'emotion': json['emotion'] == null ? undefined : json['emotion'],
    };
}

export function NewSessionRequestVoiceToJSON(value?: NewSessionRequestVoice | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'voice_id': value['voiceId'],
        'rate': value['rate'],
        'emotion': value['emotion'],
    };
}

