/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Avatar SDK
 * Heygen Streaming Avatar
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: api@heygen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewSessionIceServers2
 */
export interface NewSessionIceServers2 {
    /**
     * 
     * @type {string}
     * @memberof NewSessionIceServers2
     */
    credential?: string;
    /**
     * 
     * @type {string}
     * @memberof NewSessionIceServers2
     */
    credentialType?: string;
    /**
     * 
     * @type {string}
     * @memberof NewSessionIceServers2
     */
    username?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewSessionIceServers2
     */
    urls?: Array<string>;
}

/**
 * Check if a given object implements the NewSessionIceServers2 interface.
 */
export function instanceOfNewSessionIceServers2(value: object): value is NewSessionIceServers2 {
    return true;
}

export function NewSessionIceServers2FromJSON(json: any): NewSessionIceServers2 {
    return NewSessionIceServers2FromJSONTyped(json, false);
}

export function NewSessionIceServers2FromJSONTyped(json: any, ignoreDiscriminator: boolean): NewSessionIceServers2 {
    if (json == null) {
        return json;
    }
    return {
        
        'credential': json['credential'] == null ? undefined : json['credential'],
        'credentialType': json['credentialType'] == null ? undefined : json['credentialType'],
        'username': json['username'] == null ? undefined : json['username'],
        'urls': json['urls'] == null ? undefined : json['urls'],
    };
}

export function NewSessionIceServers2ToJSON(value?: NewSessionIceServers2 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'credential': value['credential'],
        'credentialType': value['credentialType'],
        'username': value['username'],
        'urls': value['urls'],
    };
}

