/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Avatar SDK
 * Heygen Streaming Avatar
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: api@heygen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Sdp
 */
export interface Sdp {
    /**
     * 
     * @type {string}
     * @memberof Sdp
     */
    sdp?: string;
    /**
     * 
     * @type {string}
     * @memberof Sdp
     */
    type?: SdpTypeEnum;
}


/**
 * @export
 */
export const SdpTypeEnum = {
    Answer: 'answer',
    Offer: 'offer',
    Pranswer: 'pranswer',
    Rollback: 'rollback'
} as const;
export type SdpTypeEnum = typeof SdpTypeEnum[keyof typeof SdpTypeEnum];


/**
 * Check if a given object implements the Sdp interface.
 */
export function instanceOfSdp(value: object): boolean {
    return true;
}

export function SdpFromJSON(json: any): Sdp {
    return SdpFromJSONTyped(json, false);
}

export function SdpFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sdp {
    if (json == null) {
        return json;
    }
    return {
        
        'sdp': json['sdp'] == null ? undefined : json['sdp'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function SdpToJSON(value?: Sdp | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sdp': value['sdp'],
        'type': value['type'],
    };
}

