/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Avatar SDK
 * Heygen Streaming Avatar
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: api@heygen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Sdp } from './Sdp';
import {
    SdpFromJSON,
    SdpFromJSONTyped,
    SdpToJSON,
} from './Sdp';

/**
 * 
 * @export
 * @interface StartSessionRequest
 */
export interface StartSessionRequest {
    /**
     * 
     * @type {Sdp}
     * @memberof StartSessionRequest
     */
    sdp?: Sdp;
    /**
     * 
     * @type {string}
     * @memberof StartSessionRequest
     */
    sessionId?: string;
}

/**
 * Check if a given object implements the StartSessionRequest interface.
 */
export function instanceOfStartSessionRequest(value: object): value is StartSessionRequest {
    return true;
}

export function StartSessionRequestFromJSON(json: any): StartSessionRequest {
    return StartSessionRequestFromJSONTyped(json, false);
}

export function StartSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sdp': json['sdp'] == null ? undefined : SdpFromJSON(json['sdp']),
        'sessionId': json['session_id'] == null ? undefined : json['session_id'],
    };
}

export function StartSessionRequestToJSON(value?: StartSessionRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sdp': SdpToJSON(value['sdp']),
        'session_id': value['sessionId'],
    };
}

