/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Avatar SDK
 * Heygen Streaming Avatar
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: api@heygen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StopSessionRequest
 */
export interface StopSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof StopSessionRequest
     */
    sessionId?: string;
}

/**
 * Check if a given object implements the StopSessionRequest interface.
 */
export function instanceOfStopSessionRequest(value: object): boolean {
    return true;
}

export function StopSessionRequestFromJSON(json: any): StopSessionRequest {
    return StopSessionRequestFromJSONTyped(json, false);
}

export function StopSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['session_id'] == null ? undefined : json['session_id'],
    };
}

export function StopSessionRequestToJSON(value?: StopSessionRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'session_id': value['sessionId'],
    };
}

