/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Avatar SDK
 * Heygen Streaming Avatar
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: api@heygen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StopSessionResponse
 */
export interface StopSessionResponse {
    /**
     * 
     * @type {string}
     * @memberof StopSessionResponse
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof StopSessionResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the StopSessionResponse interface.
 */
export function instanceOfStopSessionResponse(value: object): boolean {
    return true;
}

export function StopSessionResponseFromJSON(json: any): StopSessionResponse {
    return StopSessionResponseFromJSONTyped(json, false);
}

export function StopSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function StopSessionResponseToJSON(value?: StopSessionResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

