/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Avatar SDK
 * Heygen Streaming Avatar
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: api@heygen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskResponseData } from './TaskResponseData';
import {
    TaskResponseDataFromJSON,
    TaskResponseDataFromJSONTyped,
    TaskResponseDataToJSON,
} from './TaskResponseData';

/**
 * 
 * @export
 * @interface TaskResponse
 */
export interface TaskResponse {
    /**
     * 
     * @type {string}
     * @memberof TaskResponse
     */
    code?: string;
    /**
     * 
     * @type {TaskResponseData}
     * @memberof TaskResponse
     */
    data?: TaskResponseData;
    /**
     * 
     * @type {string}
     * @memberof TaskResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the TaskResponse interface.
 */
export function instanceOfTaskResponse(value: object): boolean {
    return true;
}

export function TaskResponseFromJSON(json: any): TaskResponse {
    return TaskResponseFromJSONTyped(json, false);
}

export function TaskResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : TaskResponseDataFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function TaskResponseToJSON(value?: TaskResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'data': TaskResponseDataToJSON(value['data']),
        'message': value['message'],
    };
}

