/* tslint:disable */
/* eslint-disable */
/**
 * Streaming Avatar SDK
 * Heygen Streaming Avatar
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: api@heygen.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskResponseData
 */
export interface TaskResponseData {
    /**
     * 
     * @type {number}
     * @memberof TaskResponseData
     */
    durationMs?: number;
    /**
     * 
     * @type {string}
     * @memberof TaskResponseData
     */
    taskId?: string;
}

/**
 * Check if a given object implements the TaskResponseData interface.
 */
export function instanceOfTaskResponseData(value: object): value is TaskResponseData {
    return true;
}

export function TaskResponseDataFromJSON(json: any): TaskResponseData {
    return TaskResponseDataFromJSONTyped(json, false);
}

export function TaskResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'durationMs': json['duration_ms'] == null ? undefined : json['duration_ms'],
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
    };
}

export function TaskResponseDataToJSON(value?: TaskResponseData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'duration_ms': value['durationMs'],
        'task_id': value['taskId'],
    };
}

